name: AndroidBuild
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Install Flet Tool
        # نستخدم أحدث إصدار من الأدوات
        run: |
          python -m pip install --upgrade pip
          pip install flet cookiecutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Accept Android Licenses
        run: |
          if flutter doctor --android-licenses --help > /dev/null 2>&1; then
            yes | flutter doctor --android-licenses
          fi

      - name: Prepare Project Files
        # ننقل الملفات لمجلد جديد اسمه نظيف (بدون أرقام)
        run: |
          mkdir azkar_app
          mv main.py azkar_app/
          # ننشئ ملف المتطلبات
          echo "flet" > azkar_app/requirements.txt
          # ننقل الخط والملفات الإضافية إذا وجدت
          if [ -f "myfont.otf" ]; then mv myfont.otf azkar_app/; fi
          if [ -d "assets" ]; then mv assets azkar_app/; fi

      - name: Build APK
        # هنا الحل: أضفنا --permissions android.permission.INTERNET
        # هذا السطر سيجعل المحرك يعمل وتختفي الشاشة البيضاء
        run: |
          cd azkar_app
          flet build apk --verbose --permissions android.permission.INTERNET
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AzkarApp-APK
          path: "**/*.apk"
